### ISSUE TITLE
Error: make: *** No rule to make target 'build-x86-64'.  Stop.

### ISSUE THREAD

**Issue by ecouter** [davidcallanan/os-series#62]
I used the fixes of previous post... still does not work. Im using powershell on windows 10.

PS D:\os from scratch> docker run --rm -it -v "${pwd}:/root/env" myos-buildenv
root@fba4114d7ae2:~/env# make build-x86-64
make: *** No rule to make target 'build-x86-64'.  Stop.

**Comment by ecouter** [comment]
Little update... I tried to do it on fedora with no sucess, it always show me the same error. 

PS: In linux I tried with docker and with native linux. Both shared me the same error.

**Comment by SadPersonn** [comment]
same issue

**Comment by davidcallanan** [comment]
Does using `$PWD` instead of `$(pwd)` fix the problem?

**Comment by SadPersonn** [comment]
yes thank you

**Comment by davidcallanan** [comment]
@SadPersonn Great, I will make an update for that.

**Comment by taldb** [comment]
try to change the name of the MakeFile to makefile

**Comment by mharleyaz** [comment]
Try replacing the curly braces around ${pwd} with parens.  I have had no issues with it.

DavidCallanan: Awesome tutorial!  I am greatly looking forward to the next installment!  (I assume there is one coming in the future since you are recently active here).  You have a real gift for making complex topics approachable by us mere mortals.  Well done!

**Comment by ecouter** [comment]
> 

Solved my problem. Thanks !

**Comment by ecouter** [comment]
https://github.com/davidcallanan/os-series/issues/62#issuecomment-999621387
Solved my problem. Thanks !!!
